### ISSUE TITLE
Please put a disclaimer on this code

### ISSUE THREAD

**Issue by mattwithoos** [hollandsgabe/bango#1]
I found this via the subreddit. It's pretty unethical to advertise this framework as functional and good to go when you yourself admit it's untested, and others have pointed out security holes and issues, and that you're also just a student and a JS dev primarily.

Please also follow modern PSR standards so we're not teaching new generations of PHP Devs (such as yourself) the wrong thing. Biggest example is camel_casing - it's 2020, please don't use camel case methods, and all the static calls.

Anyway a disclaimer as the first thing you read would be good - something like "This is an alpha-stage repository for a University project by a student, as such there will be security issues - do not use this in production code."

**Comment by gantoreno** [comment]
Thank you Matt, you're right. I'll update the README to clarify it from the start.
